DROP TABLE IF EXISTS comentario CASCADE;
DROP TABLE IF EXISTS tweet CASCADE;
DROP TABLE IF EXISTS usuario CASCADE;

DROP SEQUENCE IF EXISTS seq_usuario;
DROP SEQUENCE IF EXISTS seq_tweet;
DROP SEQUENCE IF EXISTS seq_comentario;